stages:
  data_ingestion:
      cmd: python src/data_ingestion.py
      deps:
        - src/data_ingestion.py
      outs:
        - data/raw/raw_data.csv
  preprocessing:
      cmd: python src/preprocessing.py
      deps:
       - data/raw/raw_data.csv
       - src/preprocessing.py
      outs:
       - data/clean_data/clean_data1.csv
  model:
      cmd: python src/model.py
      deps:
        - data/clean_data/clean_data1.csv
        - src/model.py
      outs:
        - models/model.pkl
        - data/clean_data/x_train.csv
        - data/clean_data/x_test.csv      
   